---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "prometheus-velero-exporter.fullname" . }}-statsd-mapping
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "prometheus-velero-exporter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "prometheus-velero-exporter.chart" . }}
    release: "{{ .Release.Name }}"
    {{- with .Values.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  statsd_mapping.conf: |
    mappings:
      - match: "velero.backup.active.total.*"
        name: "velero_backup_active_total"
        labels:
          schedule: "$1"
