---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "prometheus-velero-exporter.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "prometheus-velero-exporter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "prometheus-velero-exporter.chart" . }}
    release: "{{ .Release.Name }}"
    {{- with .Values.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "prometheus-velero-exporter.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "prometheus-velero-exporter.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
