---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "prometheus-velero-exporter.fullname" . }}-statsd-get
  labels:
    app.kubernetes.io/name: {{ include "prometheus-velero-exporter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "prometheus-velero-exporter.chart" . }}
    release: "{{ .Release.Name }}"
    {{- with .Values.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  statsd-get.sh: |
    #!/bin/sh
    while (sleep ${1});
    do
      for schedule in $(/velero schedule get -n {{ .Values.velero.namespace }} | grep Enabled | awk '{print $1}');
      do
        echo ${schedule};
        COUNT=0;
        COUNT=$(/velero backup get -l velero.io/schedule-name=${schedule} -n {{ .Values.velero.namespace }} | grep -v NAME | wc -l);
        statsd-client.sh  "velero.backup.active.total.${schedule}:${COUNT}|g";
      done;
    done
