---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "prometheus-velero-exporter.fullname" . }}-statsd-exporter
  labels:
    app.kubernetes.io/name: {{ include "prometheus-velero-exporter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "prometheus-velero-exporter.chart" . }}
    release: "{{ .Release.Name }}"
    {{- with .Values.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "prometheus-velero-exporter.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "prometheus-velero-exporter.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        helm.sh/chart: {{ include "prometheus-velero-exporter.chart" . }}
        {{- if .Values.podLabels }}
          {{- toYaml .Values.podLabels | nindent 8 }}
        {{- end }}
    spec:
      containers:
      - name: statsd-exporter
        image: prom/statsd-exporter
        imagePullPolicy: Always
        resources: {}
        ports:
        - containerPort: 9102
        - containerPort: 9125
        args:
          - --log.level=debug
          - --statsd.mapping-config=/etc/statsd_mapping.conf
        volumeMounts:
        - name: statsd-mapping
          mountPath: /etc/statsd_mapping.conf
          subPath: statsd_mapping.conf
      - name: velero-exporter
        args:
        - "10"
        command:
          - "/bin/statsd-get.sh"
        env:
          - name: STATSD_HOST
            value: "{{ template "prometheus-velero-exporter.fullname" . }}-statsd-exporter"
          - name: STATSD_PORT
            value: "8125"
        image: gcr.io/heptio-images/velero:v1.1.0
        imagePullPolicy: IfNotPresent
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: statsd-get
          mountPath: /bin/statsd-get.sh
          subPath: statsd-get.sh
        - name: statsd-client
          mountPath: /bin/statsd-client.sh
          subPath: statsd-client.sh
      serviceAccount: {{ template "prometheus-velero-exporter.serviceAccountName" . }}
      serviceAccountName: {{ template "prometheus-velero-exporter.serviceAccountName" . }}
      volumes:
      - name: statsd-get
        configMap:
          name: {{ template "prometheus-velero-exporter.fullname" . }}-statsd-get
          defaultMode: 0777
      - name: statsd-client
        configMap:
          name: {{ template "prometheus-velero-exporter.fullname" . }}-statsd-client
          defaultMode: 0777
      - name: statsd-mapping
        configMap:
          name: {{ template "prometheus-velero-exporter.fullname" . }}-statsd-mapping
