---
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "prometheus-velero-exporter.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ include "prometheus-velero-exporter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "prometheus-velero-exporter.chart" . }}
    release: "{{ .Release.Name }}"
    {{- with .Values.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
