---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "prometheus-velero-exporter.fullname" . }}-statsd-exporter
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "prometheus-velero-exporter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "prometheus-velero-exporter.chart" . }}
    release: "{{ .Release.Name }}"
    {{- with .Values.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: udp
    port: {{ .Values.service.port.to }} # port to push metrics to
    protocol: UDP
    targetPort: {{ .Values.service.targetPort.to }}
  - name: tcp
    port: {{ .Values.service.port.from }} # port to fetch metrics from
    protocol: TCP
    targetPort: {{ .Values.service.targetPort.from }}
  selector:
    app.kubernetes.io/name: {{ include "prometheus-velero-exporter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
