apiVersion: v1
kind: Service
metadata:
  name: {{ template "prometheus-kafka-exporter.fullname" . }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
  labels:
    app: {{ template "prometheus-kafka-exporter.name" . }}
    chart: {{ template "prometheus-kafka-exporter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: exporter-port
      protocol: TCP
      name: exporter-port
  selector:
    app: {{ template "prometheus-kafka-exporter.name" . }}
    release: {{ .Release.Name }}
